version: "3.8"

services:
  go:
    container_name: go
    build:
      context: ./golang
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root_password
    #   MYSQL_DATABASE: test_database
    #   MYSQL_USER: test_user
    #   MYSQL_PASSWORD: password
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./golang/src
        target: /go/src
    networks:
      - golang_test_network
  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    platform: linux/amd64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root_password
    #   MYSQL_DATABASE: test_database
    #   MYSQL_USER: test_user
    #   MYSQL_PASSWORD: password
    volumes:
      - type: volume
        source: mysql_test_volume
        target: /var/lib/mysql
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      # - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - golang_test_network

volumes: #ボリュームの作成
  mysql_test_volume:
    name: mysql_test_volume

networks:
  golang_test_network:
    external: true
# なぜかexitされる
# https://i.gyazo.com/d6921ead1e0affc4372fc99bb9daaf71.png
