version: "3"
services:
  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test_database"
    networks:
      - restapi-network
networks:
  restapi-network:
